# KNN
主要的思想是“物以类聚，人以群分”可以做分类，也可以做回归。
KNN做分类预测时，一般选择多数表决法
KNN做回归时，一般选择平均法

## 模型的三要素
k值的选择，距离度量，分类决策规则

### 2-K的选择:

K值的选择会对结果产生重大的影响,所以在KNN中,K就是一个需要人为调节的参数
- K选择的太小,会在较小的领域中进行选择,这样容易发生过拟合,比如k=1时,为最近邻算法.
- K选择的太大,同样会产生欠拟合
- K值最好选择的是奇数个,容易在K个结果中去"投票"
- K值的选择一般比较小

### 距离度量
欧氏距离
曼哈顿距离
闵科夫斯基距离
欧氏距离和曼哈顿距离是闵科夫斯基的距离的p = 2，p = 1的特殊情况

In [5]:
import numpy as np

In [17]:
#第一步加载数据集
def loadData(): 
    X = [[3,104],
        [2,100],
        [1,81],
        [101,10],
        [99,5],
        [98,2]] #这是一个列表
    
    Y = ['Romance','Romance','Romance','Action','Action','Action'] #也可以定义为0和1，表示一个二分类的问题
    
    return np.array(X),np.array(Y)#输出的是矩阵形式的X和y，array数组，shape代表数组的维度，后面的数字就表示是几维的

In [17]:
text_x1 = ([18,29])

In [20]:
np.shape(text_x1)

(2,)

In [18]:
X,y = loadData()

In [9]:
a = [[1,4,3,-1,6,9]]
b = np.array(a)
b.argsort()#输出的值是最后对应的索引值

array([[3, 0, 2, 1, 4, 5]])

In [10]:
np.sort(b)#从小到大排的值

array([[-1,  1,  3,  4,  6,  9]])

In [14]:
#第二步建立模型
def KNN(X,y,data,K): #data是测试样本数据
    Euclidean_distance = np.power(np.sum((data - X)**2,axis=1),0.5) #python的广播机制
    #利用欧氏距离计算两点之间的距离
    sort_k = np.argsort(Euclidean_distance)[:K]
    #np.argsort是将Euclidean_distance得到的新值对每个点距离从小到大排列,取出的是索引值
    get_K_y = y[sort_k] #变成y的标签值
    prob_dict = {} #定义一个字典
    #找概率大的
    for label in get_K_y: #循环按照大小排列好的y值
        if label not in prob_dict:
            prob_dict[label] = 1
        else:
            prob_dict[label] += 1
        predict_y = sorted(prob_dict.items(),key=lambda z:z[1],reverse=True)[0]
        #按照倒序排列
    print('predict result is {} and the probability is {}.'.format(predict_y[0],predict_y[1] / len(get_K_y)))
    
    return predict_y[0]
    

In [19]:
def a(X,y,data,k):
    a= np.power(np.sum((data - X)**2,axis=1),0.5)
    k = np.argsort(a)[:k]
    b = Y[k]
    d = {}
    for i in range(b):
        if i not in d:
            d[i] = 1
        else:
            d[i] += 1
        d = sorted(d.items(),key=lambda z:z[1],reverse=True)[0]
    return d[0]

In [20]:
data = np.array([[18,90]])
KNN(X,y,data,3)

predict result is Romance and the probability is 1.0.


'Romance'

In [16]:
sorted([36,5,-12,9,-21])#对列表中的数进行排序

[-21, -12, 5, 9, 36]

In [18]:
a = [1,5,3,6,2]
sorted(a)

[1, 2, 3, 5, 6]

In [21]:
#假如a是一个元祖构成的列表，需要用到参数key，lambda是一个隐函数
a = [('b',4),('a',0),('c',2),('d',3)]
sorted(a,key = lambda x:x[0])
#x是任意起的名字，可以使用任意的名字
#x[0]表示按照列表的第一个元素排序

[('a', 0), ('b', 4), ('c', 2), ('d', 3)]

In [25]:
a = [('b',4),('a',0),('c',2),('d',3)]
sorted(a,key = lambda x:x[0],reverse = True)[0]
#reverse = True表示按照倒序排列,[0]表示取第一个的值

('d', 3)

In [21]:
data = np.array([[18,90]])
KNN(X,y,data,3)

predict result is Romance and the probability is 1.0.


'Romance'

### 约会网站测试KNN
大概有四步，加载数据集，归一化，打乱拆分数据，建立模型


In [43]:
#加载数据集
def loadData(path):
    Train_data = []
    labels = []
    np.random.shuffle #打乱顺序函数
    
    with open(path) as f: 
#如果读取不存在的文件，就会显示出一个IOError的错误，并且给出错误码和详细的信息告诉你文件不存在。
        
        original_data = f.readlines()#读取这个文件，readlines是读取所有行
        
    for data in original_data: #循环这个文件的所有行
        data_split = data.strip('\n').split('\t') #删除数据中的\n 和 \t
        train_ = data_split[:-1] #从0位置到-1之前的数
        label_ = data_split[-1] #最后一个数字
        Train_data.append(train_) #加载到训练集的列表中
        labels.append(label_)
    
    
    return np.array(Train_data,dtype='float'),np.array(labels)

In [44]:
path = "/home/zwx/桌面/Classic_machine_learning-master/data_set/datingTestSet.txt"
X,y = loadData(path=path)

In [30]:
X.shape

(1000, 3)

In [31]:
y.shape

(1000,)

In [45]:
#归一化 标准化 特征工程
def normal(X):
    minValue = np.min(X,axis=0)#按照列求最小的
    maxValue = np.max(X,axis=0)

    newValue = (X - minValue) / (maxValue - minValue)
    #归一化的公式
    return newValue

In [46]:
Norm_X = normal(X)
Norm_X #标准化后的矩阵

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [34]:
a = np.array([[1,2,3],[4,5,6],[2,4,5],[5,6,8],[4,6,7]])
a
y = np.array([1,0,0,1,1])

In [35]:
b = np.random.permutation(a)[:2]
b

array([[4, 6, 7],
       [1, 2, 3]])

In [49]:
def split_data(X,y,pre): #这是一个拆分数据的函数
    
    # permutation: shuffling x and return index if you input real number.
    shuffle_index = np.random.permutation(X.shape[0]) #随机打乱特征值 permutation 打乱的 索引搞定
    shuffle_X = X[shuffle_index,:]
    shuffle_y = y[shuffle_index]
    
    split_index = np.int(pre * X.shape[0]) #pre是训练样本的百分比
    train_x = shuffle_X[:split_index]
    train_y = shuffle_y[:split_index]
    
    test_x = shuffle_X[split_index:]
    test_y = shuffle_y[split_index:]
    return train_x,train_y,test_x,test_y

In [50]:
train_x,train_y,test_x,test_y = split_data(Norm_X,y,0.8)

In [51]:
train_x.shape

(800, 3)

In [57]:
test_x.shape

(200, 3)

In [58]:
test_y.shape

(200,)

In [56]:
m,n = test_x.shape
print(m,n)

200 3


In [73]:
def KNN_model(train_x, test_x, train_y, test_y,K):

    accuracy = 0
    m,n = test_x.shape  #测试样本的形状 ,m = 200
    
    for i in range(m): # 循环m次，把测试样本的每一个进行比较
        
        data = test_x[i] #表示第几个样本
        
        Euclidean_distance = np.power(np.sum((data - train_x)**2,axis=1),0.5)  #算的是欧氏距离

        
        sort_k = np.argsort(Euclidean_distance)[:K]  # 索引随机排序，取第k个
        
        get_K_y = train_y[sort_k]                     #把它变成y
        
        # calculate label Probability in get_K_y.
        prob_dict = {}

        
        for label in get_K_y:
            if label not in prob_dict:
                prob_dict[label] = 1
            else:
                prob_dict[label] += 1 

        predict_y = sorted(prob_dict.items(),key=lambda z:z[1],reverse=True)[0][0]
        
        # checking predict y is right?
        if predict_y == test_y[i]:
            accuracy += 1
    print('The test set accurate is {}'.format(accuracy / len(test_y))) #正确率

In [77]:
KNN_model(train_x, test_x, train_y, test_y,5)

The test set accurate is 0.975


# 手写数字识别系统

### 分为五步
1、从文件名中把名字中后面的序号提取出来
2、文本向量化，把32*32的数字结合成1*1024
3、解析出训练数据的特征和标签向量（要用到前两步）
4、建立KNN模型
5、总的函数包括调用KNN以及用测试数据进行预测

In [5]:
from os import listdir #读取文件 os.listdir() 方法用于返回指定的文件夹包含的文件或文件夹的名字的列表
from numpy import * 
import numpy as np
import operator #调用的是操作符函数

In [6]:
#从文件名中解析分类数字
def aaa(filename1):
    bbb = filename1.split('.')[0] #得到的是filename1中字符串中第一个,（点）之前的字符串
    #参考文件名字为0_3.txt
    ccc = int(bbb.split('_')[0])#取的是3这类的数字，相当于索引
    return ccc

In [7]:
#文本向量化32*32---1*1024 把每一张图片都转换成1*1024格式
def aa(filename):
    bb = [] #把图片都放到这个新的列表中
    cc = open(filename)#打开文件
    for i in range(32):
        dd = cc.readline()
        for j in range(32):
            bb.append(int(dd[j]))
    return bb

In [11]:
#构造训练集数据向量，及对应分类标签向量
def aaaa():
    train_lable = []
    bbbb = listdir('/home/zwx/桌面/Classic_machine_learning-master/data_set/trainingDigits')
    m = len(bbbb)  #获取长度
    train_data = zeros((m,1024))#变成一个m×1024的零向量
    for i in range(m):#获取数据集的标签
        filenamestr = bbbb[i]
        train_lable.append(aaa(filenamestr))
        #%s,表示格式化一个对象为字符，将值（字符串）插入
        #[i,:]表示取出第i维下的所有数据
        train_data[i,:] = aa('/home/zwx/桌面/Classic_machine_learning-master/data_set/trainingDigits/%s' % filenamestr)
    return train_lable,train_data

In [23]:
a = [1,2,3]
b = len(a)
b

3

In [9]:
def KNN(test_data,train_data,train_lable,k):
    datasetsize = train_data.shape[0]
    #求出已知训练数据集的行数，也就是说一共有多少个样本
    
    #下面进行欧氏距离求解
    a = np.square(tile(test_data,(datasetsize,1)) - train_data) #可以用广播机制
    #tile([0,0],(1,3))表示在列的方向上重复[0,0]三次，行1次
    #在列的方向上重复1次，行的方向上重复训练集行数的次数，重复的是未知数据集
    b = np.sum(a,axis = 1)
    c = np.sqrt(b)
    d = np.argsort(c) #排序后的索引值
    e = {}
    for i in range(k): #循环k次
        f = train_lable[d[i]]#返回最小距离的索引值（关于预测值）
        e[f] = e.get(f,0) + 1 #第i+1次的预测值
        #dict = {'Name': 'Zara', 'Age': 27}
        #print "Value : dict.get('Age')
        #Value : 27
    g = sorted(e.items(),key = operator.itemgetter(1),reverse=True)
    #a = [1,2,3] 
    #b=operator.itemgetter(1)      //定义函数b，获取对象的第1个域的值
    #b(a) 
    # <<2
    return g[0][0]

In [13]:
#总的函数
def main():
    qq = int(input('输入的k值为：'))
    train_lable,train_data = aaaa()#调用函数
    testfilelist = listdir('/home/zwx/桌面/Classic_machine_learning-master/data_set/testDigits')
    l= 0
    test_number = len(testfilelist) #获取测试样本的长度
    for i in range(test_number):
        filenamestr = testfilelist[i]
        ccc = aaa(filenamestr)
        test_data = aa('/home/zwx/桌面/Classic_machine_learning-master/data_set/testDigits/%s' % filenamestr)
        ww = KNN(test_data, train_data, train_lable, qq)
        print ("第",i+1,"组：","预测值:",ww,"真实值:",ccc)
        if (ww != ccc):
            l += 1.0
    print ("\n测试集总数为:",test_number)
    print ("出错的总数为:",l)
    print ("\n错误率:",l/float(test_number)*100,'%')
if __name__ == "__main__":
    main()

输入的k值为：7
第 1 组： 预测值: 7 真实值: 7
第 2 组： 预测值: 3 真实值: 3
第 3 组： 预测值: 9 真实值: 9
第 4 组： 预测值: 2 真实值: 2
第 5 组： 预测值: 7 真实值: 7
第 6 组： 预测值: 0 真实值: 0
第 7 组： 预测值: 5 真实值: 5
第 8 组： 预测值: 7 真实值: 7
第 9 组： 预测值: 6 真实值: 6
第 10 组： 预测值: 1 真实值: 1
第 11 组： 预测值: 0 真实值: 0
第 12 组： 预测值: 9 真实值: 9
第 13 组： 预测值: 3 真实值: 3
第 14 组： 预测值: 0 真实值: 0
第 15 组： 预测值: 2 真实值: 2
第 16 组： 预测值: 3 真实值: 3
第 17 组： 预测值: 7 真实值: 7
第 18 组： 预测值: 1 真实值: 8
第 19 组： 预测值: 0 真实值: 4
第 20 组： 预测值: 3 真实值: 3
第 21 组： 预测值: 1 真实值: 1
第 22 组： 预测值: 4 真实值: 4
第 23 组： 预测值: 8 真实值: 8
第 24 组： 预测值: 4 真实值: 4
第 25 组： 预测值: 5 真实值: 5
第 26 组： 预测值: 1 真实值: 1
第 27 组： 预测值: 1 真实值: 1
第 28 组： 预测值: 0 真实值: 0
第 29 组： 预测值: 3 真实值: 3
第 30 组： 预测值: 1 真实值: 1
第 31 组： 预测值: 2 真实值: 2
第 32 组： 预测值: 6 真实值: 6
第 33 组： 预测值: 7 真实值: 7
第 34 组： 预测值: 6 真实值: 6
第 35 组： 预测值: 5 真实值: 5
第 36 组： 预测值: 5 真实值: 5
第 37 组： 预测值: 4 真实值: 4
第 38 组： 预测值: 2 真实值: 2
第 39 组： 预测值: 2 真实值: 2
第 40 组： 预测值: 1 真实值: 1
第 41 组： 预测值: 5 真实值: 5
第 42 组： 预测值: 5 真实值: 5
第 43 组： 预测值: 5 真实值: 5
第 44 组： 预测值: 9 真实值: 9
第 45 组： 预测值: 2 真实值: 2
第 46 组： 预测

第 368 组： 预测值: 6 真实值: 6
第 369 组： 预测值: 3 真实值: 3
第 370 组： 预测值: 4 真实值: 4
第 371 组： 预测值: 2 真实值: 2
第 372 组： 预测值: 4 真实值: 4
第 373 组： 预测值: 2 真实值: 2
第 374 组： 预测值: 4 真实值: 4
第 375 组： 预测值: 9 真实值: 9
第 376 组： 预测值: 5 真实值: 5
第 377 组： 预测值: 4 真实值: 4
第 378 组： 预测值: 1 真实值: 1
第 379 组： 预测值: 3 真实值: 3
第 380 组： 预测值: 9 真实值: 9
第 381 组： 预测值: 6 真实值: 6
第 382 组： 预测值: 1 真实值: 1
第 383 组： 预测值: 8 真实值: 8
第 384 组： 预测值: 6 真实值: 6
第 385 组： 预测值: 8 真实值: 8
第 386 组： 预测值: 5 真实值: 5
第 387 组： 预测值: 9 真实值: 3
第 388 组： 预测值: 0 真实值: 0
第 389 组： 预测值: 8 真实值: 8
第 390 组： 预测值: 1 真实值: 1
第 391 组： 预测值: 8 真实值: 8
第 392 组： 预测值: 3 真实值: 3
第 393 组： 预测值: 8 真实值: 8
第 394 组： 预测值: 3 真实值: 3
第 395 组： 预测值: 4 真实值: 4
第 396 组： 预测值: 3 真实值: 3
第 397 组： 预测值: 4 真实值: 4
第 398 组： 预测值: 6 真实值: 5
第 399 组： 预测值: 2 真实值: 2
第 400 组： 预测值: 7 真实值: 7
第 401 组： 预测值: 5 真实值: 5
第 402 组： 预测值: 4 真实值: 4
第 403 组： 预测值: 9 真实值: 9
第 404 组： 预测值: 9 真实值: 9
第 405 组： 预测值: 1 真实值: 1
第 406 组： 预测值: 9 真实值: 9
第 407 组： 预测值: 6 真实值: 6
第 408 组： 预测值: 5 真实值: 5
第 409 组： 预测值: 5 真实值: 5
第 410 组： 预测值: 0 真实值: 0
第 411 组： 预测

第 726 组： 预测值: 4 真实值: 4
第 727 组： 预测值: 7 真实值: 7
第 728 组： 预测值: 7 真实值: 7
第 729 组： 预测值: 8 真实值: 8
第 730 组： 预测值: 9 真实值: 5
第 731 组： 预测值: 3 真实值: 3
第 732 组： 预测值: 8 真实值: 8
第 733 组： 预测值: 0 真实值: 0
第 734 组： 预测值: 1 真实值: 1
第 735 组： 预测值: 7 真实值: 7
第 736 组： 预测值: 4 真实值: 4
第 737 组： 预测值: 2 真实值: 2
第 738 组： 预测值: 5 真实值: 5
第 739 组： 预测值: 8 真实值: 8
第 740 组： 预测值: 4 真实值: 4
第 741 组： 预测值: 5 真实值: 5
第 742 组： 预测值: 2 真实值: 2
第 743 组： 预测值: 2 真实值: 2
第 744 组： 预测值: 2 真实值: 2
第 745 组： 预测值: 1 真实值: 1
第 746 组： 预测值: 8 真实值: 8
第 747 组： 预测值: 3 真实值: 3
第 748 组： 预测值: 6 真实值: 6
第 749 组： 预测值: 2 真实值: 2
第 750 组： 预测值: 8 真实值: 8
第 751 组： 预测值: 0 真实值: 0
第 752 组： 预测值: 5 真实值: 5
第 753 组： 预测值: 0 真实值: 0
第 754 组： 预测值: 7 真实值: 7
第 755 组： 预测值: 2 真实值: 2
第 756 组： 预测值: 0 真实值: 0
第 757 组： 预测值: 2 真实值: 2
第 758 组： 预测值: 0 真实值: 0
第 759 组： 预测值: 6 真实值: 6
第 760 组： 预测值: 1 真实值: 1
第 761 组： 预测值: 8 真实值: 8
第 762 组： 预测值: 7 真实值: 7
第 763 组： 预测值: 5 真实值: 5
第 764 组： 预测值: 6 真实值: 6
第 765 组： 预测值: 5 真实值: 5
第 766 组： 预测值: 9 真实值: 9
第 767 组： 预测值: 9 真实值: 9
第 768 组： 预测值: 0 真实值: 0
第 769 组： 预测

In [ ]:
X = [[3,104],
        [2,100],
        [1,81],
        [101,10],
        [99,5],
        [98,2]]
Y = [0,0,0,1,1,1]

In [87]:
y = np.array(Y)
x = np.array(X)
print (y)

[0 0 0 1 1 1]


In [88]:
text_x2 = np.array([[18,90]])

In [89]:
a = np.sum((text_x2 - X)**2,axis = 1)

In [90]:
print(a)

[  421   356   370 13289 13786 14144]


In [91]:
b = np.power(a,0.5)

In [92]:
print(b)

[ 20.51828453  18.86796226  19.23538406 115.27792503 117.41379817
 118.92854998]


In [93]:
d = np.argsort(b)

In [94]:
print(d)

[1 2 0 3 4 5]


In [97]:
e = y[d]
print(e)

[0 0 0 1 1 1]


In [ ]:
path = 地址
X = []
Y = []
with open(path,'r') as f:
    lines = f.readlines()
    for i in lines:
        line = i.strip('\n').split('\t')
        
        #print(i.strip('\n').split('\t'))
        X.append(np.float(line[0]),np.float(line[1]),np.float(line[2]))
        Y.append(line[-1])
X = np.array(X) 
Y = np.array(Y)
print(X.shape)
print(Y.shape)